<a href="https://colab.research.google.com/github/GHK16/PytorchTutorial/blob/main/mathop.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import numpy as np

In [3]:
tensor_a=torch.tensor([1,2,3,4])
tensor_b=torch.tensor([5,6,7,8])
tensor_a+tensor_b

tensor([ 6,  8, 10, 12])

In [4]:
torch.add(tensor_a,tensor_b)

tensor([ 6,  8, 10, 12])

In [5]:
tensor_b-tensor_a

tensor([4, 4, 4, 4])

In [6]:
torch.sub(tensor_b,tensor_a)

tensor([4, 4, 4, 4])

In [7]:
tensor_a*tensor_b

tensor([ 5, 12, 21, 32])